### ISSUE TITLE
Add parser tests causing memory grow of control_stack

### ISSUE THREAD

**Issue by chfast** [wasmx/fizzy#321]
Oops, I have not see this. In this case this is fine as we use `std::deque`, but still I should have think about this before :) I guess I need some tests that causes stack memory grow here and then ASan should find the bug, if it ever happen.

_Originally posted by @chfast in https://github.com/wasmx/fizzy/pull/319/review_comment/create_

**Comment by gumb0** [comment]
For me in #312 control stack using `Stack` often reallocates even when growing from size 1 to 2 (in Debug).
For example if order of `frame` updating and `push` is reversed here, some unit tests are failing (e.g. `execute_control.br_table_as_return`)
https://github.com/wasmx/fizzy/blob/9fa554ffa18699e55d072b47707af2f23c7de30b/lib/fizzy/parser_expr.cpp#L298-L303

**Comment by chfast** [comment]
I checked all 3 cases in `block`, `loop` and `if`. If `frame` used after `control_stack.push()` and `std::vector` used as `std::stack` backend, all are causing ASan failures when running `execute_control` test suite.
