### ISSUE TITLE
Limit verbosity of fizzy-spectests

### ISSUE THREAD

**Issue by chfast** [wasmx/fizzy#450]
The output from `fizzy-spectests` is quite large as it reports status of every executed test case. I expect users are mostly interested in failures. Some ideas how to improve it.

1. Skip `PASSED` reports by default. Easy to implement.
2. Repeat status of each file in the end. This will allow at least quickly find the file with failures and repeat the run on the subset of files.
3. Use "dot notation" per file. Each test result is represented by a single character. E.g.
   ```
   binary.wast: ......F.....s.....
   Line 98: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
   Line 99: assert_return SKIPPED Unsupported feature: Floating point instruction.
   ```

**Comment by axic** [comment]
I like a combination of 1. and 3.:
- display it like you propose in 3.
- do not display SKIPPED by default, but add an option `--show-skipped` to show them
