### ISSUE TITLE
Change unary operations to operate on OperandStack::top and not pop/push

### ISSUE THREAD

**Issue by axic** [wasmx/fizzy#463]

**Comment by chfast** [comment]
An alternative, what would be compatible with "unsafe host functions" is to pass pointer to the top stack item.

```cpp
void unary_op(Value* top)
{
    *top = op(*top);
}
```

**Comment by chfast** [comment]
This is done.

**Comment by axic** [comment]
Which PR?

**Comment by axic** [comment]
Right I see in `unary_op`.

**Comment by axic** [comment]
Could also do a similar experiment to evmone in `binary_op`/`comparison_op` to only pop one and overwrite the other.

**Comment by chfast** [comment]
In https://github.com/wasmx/fizzy/commit/998fab6f601c0b281603181ab4b4c72615dad7d9.

> Could also do a similar experiment to evmone in `binary_op`/`comparison_op` to only pop one and overwrite the other.

This is already done this way.

**Comment by axic** [comment]
Damn, probably had an old code checked out locally when I looked.
