### ISSUE TITLE
Extend instantiate() with a memory limit

### ISSUE THREAD

**Issue by axic** [wasmx/fizzy#509]
This would replace the hard `MemoryPagesLimit` in `limits.h`. If no limit is set by the user, it defaults to `MemoryPagesLimit` (256Mb). If it is set higher than 2^32-1 return an error (or just make the limit uint32).

Also set this limit to 4Gb in spectests in order to pass them.

**Comment by gumb0** [comment]
1. 4Gb limit is already enforced by validation, do we want a new error raised when incorrect limit passed to `instantiate`?

2. `memory.grow` currently also aborts when exceeding `MemoryPagesLimit`. We would need to save the hard limit to `Instance` to use it in execute, too.

**Comment by axic** [comment]
All we want is a new configurable limit (part of the Instance). We can default to our 256Mb limit if it is not set my the user.
