### ISSUE TITLE
Optimize fN.abs, fN.neg, fN.copysign instructions

### ISSUE THREAD

**Issue by chfast** [wasmx/fizzy#540]
The goal is to have the simplest and leanest implementation of the following WebAssembly instructions:
- `f32.abs`, `f64.abs`
- `f32.neg`, `f64.neg`
- `f32.copysign`, `f64.copysign`

Current implementation uses C/C++ standard functions to implement the core of the instructions: `std::fabs`, `std::copysign` and `-x` for negation. Due to compilers optimization pipelines, this does not provide optimal implementation: the generated code sometimes unnecessary uses floating-point or SSE2 instructions.

Change the implementation to use matching unsigned integer types and bit manipulation.

E.g. for `f32.abs` it is enough to zero the most significant bit of the unsigned integer representation of the value.

```cpp
float fabs(float a) noexcept
{
    return bit_cast<float>(bit_cast<uint32_t>(a) & 0x7fffffff);
}
```

Here are some additional tips and hints: https://godbolt.org/z/KaET9c.

**Comment by Themarek1** [comment]
Hello is this issue still open, if it is can i work on it ?

**Comment by chfast** [comment]
Yes, start with something small like single case.
