### ISSUE TITLE
Make use of C++20 bit manipulation features

### ISSUE THREAD

**Issue by axic** [wasmx/fizzy#543]
We are currently using compiler builtins:
- `__builtin_clz`
- `__builtin_clzll`
- `__builtin_ctz`
- `__builtin_ctzll`
- `__builtin_popcount`
- `__builtin_popcountll`

These can be replaced with the new C++20 features proposed (see https://en.cppreference.com/w/cpp/numeric).

For an idea how to write such a wrapper, check out `lib/fizzy/cxx20/span.hpp`.

**Comment by herobank110** [comment]
Hello, I have been reading about c++20 features and would like to try solve this issue.

**Comment by chfast** [comment]
Hi @herobank110,

you can start with a simple task as follows:
- move the implementation of `popcount` (https://github.com/wasmx/fizzy/blob/master/lib/fizzy/execute.cpp#L328-L331) to `cxx20/bit.hpp`
- make it's function signature exactly as in C++20: https://en.cppreference.com/w/cpp/numeric/popcount.

**Comment by chfast** [comment]
Correction, start with something other than `popcount` as it is being done in #551.

**Comment by herobank110** [comment]
I made an wrapper of countl_zero. Please can you check it? #570
