### ISSUE TITLE
Create a CI job for little endian ARM

### ISSUE THREAD

**Issue by axic** [wasmx/fizzy#710]
Ideally we would want to [support Apple Silicon](https://github.com/wasmx/fizzy/issues/709), it seems CircleCI may [not support it anytime soon](https://support.circleci.com/hc/en-us/articles/360047734172-Can-I-build-Apple-Silicon-Universal-apps-). Hence the next best option we have is to run a CI job with Linux and qemu for little endian ARM.

**Comment by jakelang** [comment]
https://www.scaleway.com/en/hello-m1/ @axic

**Comment by axic** [comment]
@jakelang thanks, looks cool! I couldn't find the CI/CD part on it though, only mentioned on the front page.

**Comment by axic** [comment]
CircleCI supports now building (as they have newer XCode), but not running: https://support.circleci.com/hc/en-us/articles/360056461452-Apple-M1-Apple-Silion-Support-on-CircleCI
