### ISSUE TITLE
Does fizzy have any plans to support fix-width SIMD?

### ISSUE THREAD

**Issue by iLoveTangY** [wasmx/fizzy#842]

**Comment by axic** [comment]
We do not plan to implement it, but may be able to review external PRs. If someone does end up making an external contribution, please first only implement a few instructions to allow early feedback.

**Comment by iLoveTangY** [comment]
> We do not plan to implement it, but may be able to review external PRs. If someone does end up making an external contribution, please first only implement a few instructions to allow early feedback.

Thanks for your answer!
